In [4]:
import numpy as np

print("Task 1: Maximum and Minimum Value of Flattened Array")

arr = np.array([[0, 1], [2, 3]])
print("Original flattened array:")
print(arr)

max_val = arr.max()
min_val = arr.min()

print("Maximum value of the above flattened array:", max_val)
print("Minimum value of the above flattened array:", min_val)


Task 1: Maximum and Minimum Value of Flattened Array
Original flattened array:
[[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [5]:
print("Task 2: 3x3 Matrix with values from 2 to 10")

matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


Task 2: 3x3 Matrix with values from 2 to 10
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
print("Task 3: Convert Array to Float Type")

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

float_arr = arr.astype(float)
print("Array converted to float type:", float_arr)


Task 3: Convert Array to Float Type
Original array: [1 2 3 4]
Array converted to float type: [1. 2. 3. 4.]


In [7]:
print("Task 4: Multiply 2x2 Matrices and Take Transpose")

A = np.array([[5, 5], [1, 1]])
B = np.array([[1, 2], [0, 1]])

result = np.dot(A, B)
print("Resultant Matrix:")
print(result)

transpose = result.T
print("Transpose of Resultant Matrix:")
print(transpose)


Task 4: Multiply 2x2 Matrices and Take Transpose
Resultant Matrix:
[[ 5 15]
 [ 1  3]]
Transpose of Resultant Matrix:
[[ 5  1]
 [15  3]]


In [8]:
print("Task 5: Find Inverse of Matrix")

matrix = np.array([
    [6, 1, 1, 3],
    [4, -2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
])

inverse_matrix = np.linalg.inv(matrix)
print("Inverse of the matrix:")
print(inverse_matrix)


Task 5: Find Inverse of Matrix
Inverse of the matrix:
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
